### ISSUE TITLE
Swift 3.0 support needed

### ISSUE THREAD

**Issue by wirakoon78** [microsoftgraph/ios-swift-faceapi-sample#1]
Thanks for the great sample code, but do you by any chance know this doesn't work on Swift3.0?

**Comment by unpluggedk** [comment]
hey, this sample was made for Swift2.x using Xcode 7. 
so, as is, it will not work on Swift3 as the new Swift3 contains breaking changes.

However, we plan to update the sample sooner rather than later to have it work on Swift3!

Most of the workflow will/should intact though.

Thanks!
