### ISSUE TITLE
Service error : "RateLimitExceeded"

### ISSUE THREAD

**Issue by wirakoon78** [microsoftgraph/ios-swift-faceapi-sample#2]
Hi 

I use Find Similar api : https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395237

to find similar faces. 
I uploaded 148 photos but always get this error from the server .

{ "error":{ "statusCode": 429, "message": "Rate limit is exceeded. Try again later." } }"

I have no idea what the problem is . Could you please let me know what the issue is . 
Thanks in advance.

**Comment by jamescro** [comment]
Sorry it took us so long to respond. As I understand it you have a technical question about the Find Similar API, which is a Cognitive Services API. Please ask your question on stackoverflow.com. Tag your question "microsoft-cognitive."
