### ISSUE TITLE
Not compatible in swift 4.0

### ISSUE THREAD

**Issue by chandanmishra1995** [microsoftgraph/ios-swift-faceapi-sample#4]
Hello all
Please provide this SDK on swift 4.0 for Xcode 9 
as it is not working in swift 9.0
Thanks 
Chandan Mishra

**Comment by JohnMAustin78** [comment]
Hello Chandran,

I've added a backlog item to migrate this sample to XCode 9 and Swift 4.  Thank you for bringing this to our attention.

John

**Comment by jasonjoh** [comment]
It is compatible with latest Xcode and Swift 4.0 as of now.
